### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by martoio** [Berava/prj-rev-bwfs-dasmoto#2]
Make sure you implement proper indentation in your code to ease readability and show any parent-child relationships between the elements.
https://www.granneman.com/webdev/coding/formatting-and-indenting-your-html/
https://github.com/Berava/prj-rev-bwfs-dasmoto/blob/792d0fa8092294b8d9a8c324495c53e26597033f/dasmoto/index.html#L13-L15

**Comment by Berava** [comment]
You're right, i forgot this one ! Again thank you for the URL.
